import {buildEvents,addDays,localNow,duration} from './lib.js';
import {loadDay,notificationSettings} from './db.js';
import {summaryText} from './render.js';
import {send,edit} from './telegram.js';
const TZ='Europe/Kyiv';
export async function notifyMenu(env,chat,msgId=null){const s=await notificationSettings(env,chat);const text=`🔔 <b>Персональні сповіщення</b>\n\n⚡💧 Вода + світло: ${s.both_alerts?'✅':'❌'}\n💧 Вода: ${s.water_alerts?'✅':'❌'}\n⚠️ Перед завершенням: ${s.end_alerts?'✅':'❌'}\n⏱ Попереджати за: <b>${s.lead_minutes} хв</b>\n⏳ Мінімальне вікно: <b>${Number(s.min_window_minutes||0)?duration(s.min_window_minutes):'будь-яке'}</b>\n🌅 Ранкове зведення: ${s.morning_summary?'✅':'❌'}\n🌙 Графік на завтра ввечері: ${s.evening_summary?'✅':'❌'}`;const kb={inline_keyboard:[[{text:`⚡💧 ${s.both_alerts?'✅':'❌'}`,callback_data:'n:t:both'},{text:`💧 ${s.water_alerts?'✅':'❌'}`,callback_data:'n:t:water'}],[{text:`⚠️ Кінець ${s.end_alerts?'✅':'❌'}`,callback_data:'n:t:end'}],[15,30,60].map(x=>({text:`${Number(s.lead_minutes)===x?'✅ ':''}${x} хв`,callback_data:`n:l:${x}`})),[0,60,120].map(x=>({text:`${Number(s.min_window_minutes||0)===x?'✅ ':''}${x===0?'будь-яке':x/60+' год+'}`,callback_data:`n:m:${x}`})),[{text:`🌅 Ранок ${s.morning_summary?'✅':'❌'}`,callback_data:'n:t:morning'},{text:`🌙 Завтра ${s.evening_summary?'✅':'❌'}`,callback_data:'n:t:evening'}]]};return msgId?edit(env,chat,msgId,text,kb):send(env,chat,text,{reply_markup:kb});}
export async function notificationCallback(env,chat,msgId,d){const parts=d.split(':');if(parts[1]==='l')await env.DB.prepare('UPDATE notification_settings SET lead_minutes=?,updated_at=CURRENT_TIMESTAMP WHERE chat_id=?').bind(+parts[2],chat).run();if(parts[1]==='m')await env.DB.prepare('UPDATE notification_settings SET min_window_minutes=?,updated_at=CURRENT_TIMESTAMP WHERE chat_id=?').bind(+parts[2],chat).run();if(parts[1]==='t'){const col={both:'both_alerts',water:'water_alerts',end:'end_alerts',morning:'morning_summary',evening:'evening_summary'}[parts[2]];if(col)await env.DB.prepare(`UPDATE notification_settings SET ${col}=CASE ${col} WHEN 1 THEN 0 ELSE 1 END,updated_at=CURRENT_TIMESTAMP WHERE chat_id=?`).bind(chat).run();}return notifyMenu(env,chat,msgId);}
export async function notifyAll(now,env){const n=localNow(now,TZ),r=await env.DB.prepare('SELECT * FROM notification_settings').all();for(const s of r.results||[]){try{const a=await loadDay(env,n.date);if(a)for(const e of buildEvents(a,s,n.date)){if(Math.abs(e.minute-n.minute)<=2)await onceNotify(env,s.chat_id,e.key,e.text);}if(s.morning_summary&&Math.abs(n.minute-480)<=2&&a)await onceNotify(env,s.chat_id,`${n.date}:morning`,`${summaryText('СЬОГОДНІ',n.date,a)}\n\nГарного дня!`);if(s.evening_summary&&Math.abs(n.minute-1200)<=2){const d=addDays(n.date,1),t=await loadDay(env,d);if(t)await onceNotify(env,s.chat_id,`${d}:evening`,`${summaryText('ЗАВТРА',d,t)}\n\n🔔 Це ваше вечірнє зведення.`);}}catch(e){console.log('notify',e);}}}
async function onceNotify(env,chat,key,text){const r=await env.DB.prepare('INSERT OR IGNORE INTO notification_log(chat_id,event_key,event_at) VALUES(?,?,CURRENT_TIMESTAMP)').bind(String(chat),key).run();if(r.meta?.changes)await send(env,String(chat),text);}
